### ISSUE TITLE
Stop on escape key

### ISSUE THREAD

**Issue by CMurtagh-LGTM** [gsuuon/tshjkl.nvim#15]
I was wondering if there was a way to stop navigating when I press escape.

Here's my current config
```
select_current_node = false
keymaps = { toggle = "<leader>T" }
```
it does not make sense in my brain to press "<leader>T" to also disable the plugin.

**Comment by gsuuon** [comment]
I just added some functionality for this (though `select_current_node` before would also do what you want). I also find myself reaching for `q` to pop out of tshjkl if I'm not using `select_current_node`. This update makes it possible to access and set the current node directly (e.g. to find and set the first function parent) as well, and keybinds can be set per buffer. Check out the [updated docs](https://github.com/gsuuon/tshjkl.nvim?tab=readme-ov-file#binds).
