### ISSUE TITLE
Trouble remapping toggle

### ISSUE THREAD

**Issue by petrisch** [gsuuon/tshjkl.nvim#3]
Hi,

Very cool plugin! Exactly what I was looking for. Just toggle to tree-sitter navigation. Go in and out without having to think about what is a node, and do what I want with it, very cool.

Since I use Alacritty and <Alt-v> is tied to a new window, I have trouble remapping:
Here is what I have:

```
require('tshjkl').setup({
	  default_config = {
	  select_current_node = true, -- false to highlight only
	  keymaps = {
	    toggle = '<leader>N',
          },
        }
})
```
But it doesn't work. Am I doing it wrong?
using `require('gsuuon/tshjkl.nvim').setup` doesn't work either.
I'm not the lua expert, so maybe I'm just totaly wrong.

**Comment by gsuuon** [comment]
Hi! Try without putting everything in `default_config`
```lua
require('tshjkl').setup({
  keymaps = {
    toggle = '<leader>N',
  }
})
```

**Comment by petrisch** [comment]
Yes that was it!
Thanks alot
