### ISSUE TITLE
feat: Expose a programmatic api

### ISSUE THREAD

**Issue by mikavilpas** [gsuuon/tshjkl.nvim#7]
Hi! 👋🏻 
Love this plugin. I wanted to write a plugin like this myself but was very happy to find that you already did.

I was wondering how you would feel about exposing the functions used by the keybindings in [init.lua](https://github.com/gsuuon/tshjkl.nvim/blob/main/lua/tshjkl/init.lua#L226-L333).

This could allow users to use them in a clean way in case they would like to write something custom.

In case you feel this would be a good idea, I might be able to contribute this change. I am new to neovim but have used vim in my development work a long time ago.

side note: I worked with a similar plugin for emacs and created vim bindings for it in [evil-lispy](https://github.com/sp3ctum/evil-lispy), although I used that for elisp and clojure at the time.

**Comment by gsuuon** [comment]
Hi, glad you're enjoying the plugin! I think that's a great idea, feel free to open a PR.

**Comment by gsuuon** [comment]
I think this was closed along with #15 by 19d65d4, but feel free to re-open if you had something else in mind!
